export const SET_BOOK_INFO = 'SET_BOOK_INFO';
export const SUBMIT_BOOK_INFO = 'SUBMIT_BOOK_INFO';
export const CLEAR_CURRENT_BOOK_INFO = 'CLEAR_CURRENT_BOOK_INFO';
export const DELETE_BOOK = 'DELETE_BOOK';
export const ADD_BOOK_IN_LIST = 'ADD_BOOK_IN_LIST';